name: Dispatch update to statgarten/dockerImage

on: [push]

jobs:
  update-dockerImage:
    name: "Dispatch update to statgarten/dockerImage"
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date={$(date +'%Y%m%d')}" >> $GITHUB_ENV
      - name: Send Trigger
        run: |
          curl -X POST https://api.github.com/repos/statgarten/dockerImage/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'X-GitHub-Api-Version: 2022-11-28'
          -u ${{ secrets.ACCESS_TOKEN }} \
          -d '{"event_type": "statgarten_update", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "tag": ${{ env.date }}}}'
